Chat entity
bsolomko/chat pull request #24
Opened 2021-04-12 12:53 UTC by SerhiiPoliakov1

2021-04-12 18:23 UTC, bsolomko commented
pls format

2021-04-12 18:38 UTC, bsolomko requested changes

2021-04-12 18:38 UTC, bsolomko commented on src/main/java/co/norse/chat/controller/ChatController.java
> +        Message _message = new Message();
rename _message to messageModel

2021-04-12 18:38 UTC, bsolomko commented on src/main/java/co/norse/chat/controller/ChatController.java
> +    @PostMapping("/user/{id}/chat/{chatId}/message/send/{recipientId}")
i'd rather redisign it /char/{chatId} and pass all params as requestBody

2021-04-12 18:38 UTC, bsolomko commented on src/main/java/co/norse/chat/controller/ChatController.java
> +    @GetMapping("/user/{id}/chat/{chatId}/message")
same here

2021-04-12 18:38 UTC, bsolomko commented on src/main/java/co/norse/chat/controller/ChatController.java
> +    List<Message> messages = chat.getMessages();
inline

2021-04-12 18:38 UTC, bsolomko commented on src/main/java/co/norse/chat/model/Chat.java
> +public class Chat {
hashcode equals etc

2021-04-12 18:38 UTC, bsolomko commented on src/main/java/co/norse/chat/repository/ChatRepository.java
> +    public List<Chat> getAllChat(){
getAllChats

2021-04-12 18:38 UTC, bsolomko commented on src/main/java/co/norse/chat/repository/ChatRepository.java
> +        this.chatStore = chatStore.stream().filter(chat -> chat.getId() != id).collect(Collectors.toList());
remove this

2021-04-12 18:38 UTC, bsolomko commented on src/main/java/co/norse/chat/repository/ChatRepository.java
> +        this.chatStore.clear();
same here

2021-04-12 18:38 UTC, bsolomko commented on src/main/java/co/norse/chat/repository/ChatRepository.java
> +    public void deleteAllChat(){
deleteAllChats

2021-04-12 18:38 UTC, bsolomko commented on src/main/java/co/norse/chat/repository/ChatRepository.java
> +    public Chat getChatByID(long id){
getChatById

2021-04-13 12:57 UTC, SerhiiPoliakov1 reviewed
accept

2021-04-13 12:57 UTC, SerhiiPoliakov1 commented on src/main/java/co/norse/chat/model/Chat.java
> +public class Chat {
accept

2021-04-13 14:35 UTC, bsolomko approved these changes

2021-04-13 14:36 UTC, merged